version: "3.2"
services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    env_file: ./backend/core/settings/.env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: pipenv run python manage.py runserver 0.0.0.0:8000 --settings=core.settings.dev
    depends_on:
        - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
  
  # Container to test the prod build.
  prod:
    build: .
    volumes:
      # Used to generate the requirements.txt for prod.
      - ./requirements.txt
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - PORT=8000
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=clave_secreta
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

volumes:
  postgres_data: