version: "3.2"
services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    environment:
      - DEBUG=1
      - SECRET_KEY=clave_secreta
      - DATABASE_TYPE=url
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    depends_on:
        - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

volumes:
  postgres_data: